import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-primary-fixed-variant": "#3f465c",
        "on-error-container": "#93000a",
        "error": "#ba1a1a",
        "surface-variant": "#e0e3e5",
        "secondary-container": "#86f2e4",
        "surface-bright": "#f7f9fb",
        "inverse-primary": "#bec6e0",
        "outline": "#76777d",
        "secondary-fixed-dim": "#6bd8cb",
        "on-primary-container": "#7c839b",
        "tertiary": "#000000",
        "background": "#f7f9fb",
        "on-primary": "#ffffff",
        "on-secondary-fixed": "#00201d",
        "secondary": "#006a61",
        "on-secondary-container": "#006f66",
        "on-secondary": "#ffffff",
        "primary-container": "#131b2e",
        "surface-tint": "#565e74",
        "on-tertiary-container": "#b87500",
        "on-primary-fixed": "#131b2e",
        "primary-fixed-dim": "#bec6e0",
        "secondary-fixed": "#89f5e7",
        "on-surface": "#191c1e",
        "tertiary-fixed": "#ffddb8",
        "on-background": "#191c1e",
        "on-secondary-fixed-variant": "#005049",
        "on-surface-variant": "#45464d",
        "surface-dim": "#d8dadc",
        "on-tertiary-fixed-variant": "#653e00",
        "on-error": "#ffffff",
        "surface-container": "#eceef0",
        "surface-container-high": "#e6e8ea",
        "tertiary-fixed-dim": "#ffb95f",
        "surface-container-low": "#f2f4f6",
        "on-tertiary-fixed": "#2a1700",
        "surface": "#f7f9fb",
        "primary-fixed": "#dae2fd",
        "inverse-on-surface": "#eff1f3",
        "error-container": "#ffdad6",
        "tertiary-container": "#2a1700",
        "inverse-surface": "#2d3133",
        "surface-container-highest": "#e0e3e5",
        "surface-container-lowest": "#ffffff",
        "outline-variant": "#c6c6cd",
        "primary": "#000000",
        "on-tertiary": "#ffffff",
        "brand-deep-blue": "#0F172A",
        "brand-teal": "#0D9488",
        "brand-amber": "#F59E0B",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1.5rem",
        full: "9999px",
      },
      spacing: {
        lg: "40px",
        xs: "4px",
        md: "24px",
        sm: "12px",
        xl: "64px",
        base: "8px",
        safe: "env(safe-area-inset-bottom, 20px)",
        "container-max": "1200px",
      },
      fontFamily: {
        sans: ["Plus Jakarta Sans", "sans-serif"],
        "display-lg": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "label-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Plus Jakarta Sans", "sans-serif"],
        "label-sm": ["Plus Jakarta Sans", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "60px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
      },
      animation: {
        "slide-up": "slideUp 0.6s cubic-bezier(0.16, 1, 0.3, 1) forwards",
        "pulse-slow": "pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite",
        "bounce-gentle": "bounceGentle 2s infinite",
      },
      keyframes: {
        slideUp: {
          "0%": { opacity: "0", transform: "translateY(24px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        bounceGentle: {
          "0%, 100%": { transform: "translateY(-10%)", animationTimingFunction: "cubic-bezier(0.8,0,1,1)" },
          "50%": { transform: "none", animationTimingFunction: "cubic-bezier(0,0,0.2,1)" },
        },
      },
    },
  },
  plugins: [],
};
export default config;
